### ISSUE TITLE
When I run the user.py inside the example, the following error occurs

### ISSUE THREAD

**Issue by beiji-zz** [Helix-ex/sdk#1]
nohup: ignoring input

User error: #401 - {"error":{"code":8,"message":"Authentication verification error: actix-web error: credentials have expired"}}

Huid: None

User error: #401 - {"error":{"code":8,"message":"Authentication verification error: actix-web error: credentials have expired"}}
BTC deposit address: None

User error: #401 - {"error":{"code":8,"message":"Authentication verification error: actix-web error: credentials have expired"}}
ETH deposit address: 0xNone

User error: #401 - {"error":{"code":8,"message":"Authentication verification error: actix-web error: credentials have expired"}}
Traceback (most recent call last):
  File "/root/sdk/pyHelixMarkets/user.py", line 30, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/sdk/pyHelixMarkets/user.py", line 14, in main
    print(f'ICP deposit address (principal id): {user.GetDepositAddress("icp")[0]}')
TypeError: 'NoneType' object is not subscriptable

**Comment by beiji-zz** [comment]
I solved it, but how is the price of swap calculated?
![image](https://github.com/Helix-ex/sdk/assets/13294270/f7f80fcd-0b7c-443d-b62a-a0aa730fb032)
